title:  Parniyan Darakhshan
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
 Welcome to my portfolio! Here you will find examples of my work, skills, and experiences. I hope you enjoy exploring and getting to know me better.
  <br><br><br>
  <a href="linkedin.com/in/parniyan-darakhshan">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal   
 
